# Generated by Django 5.2.8 on 2025-11-18 13:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('data_access', 'Accès aux données'), ('data_export', 'Export de données'), ('data_ingestion', 'Ingestion de données'), ('admin_config', 'Configuration admin'), ('pipeline_manage', 'Gestion pipelines'), ('api_consume', 'Consommation API'), ('audit_view', 'Visualisation audit')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'users_permission',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('admin_platform', 'Administrateur Plateforme'), ('data_engineer', 'Ingénieur Data/ETL'), ('analyst_economist', 'Analyste/Économiste'), ('reader_stakeholder', 'Lecteur (Stakeholder)'), ('api_client', 'Client API Externe')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('organization', models.CharField(blank=True, help_text="Organisation de l'utilisateur", max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mfa_enabled', models.BooleanField(default=False, help_text='MFA activé')),
                ('mfa_secret', models.CharField(blank=True, help_text='Secret TOTP pour MFA', max_length=32)),
                ('mfa_backup_codes', models.JSONField(blank=True, default=list, help_text='Codes de secours MFA')),
                ('api_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('api_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('api_rate_limit', models.IntegerField(default=1000, help_text='Requêtes API par heure')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role')),
            ],
            options={
                'db_table': 'users_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('data_access', 'Accès aux données'), ('data_export', 'Export de données'), ('data_ingestion', 'Ingestion de données'), ('config_change', 'Modification configuration'), ('pipeline_run', 'Exécution pipeline'), ('api_call', 'Appel API'), ('permission_change', 'Modification permissions')], max_length=50)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], default='info', max_length=20)),
                ('resource', models.CharField(blank=True, help_text='Ressource affectée (ex: source, indicateur)', max_length=200)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Détails supplémentaires')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='users_audit_timesta_93fd2e_idx'), models.Index(fields=['action', 'level'], name='users_audit_action_4b2a91_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataSourceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('BRVM', 'BRVM'), ('WorldBank', 'Banque Mondiale'), ('IMF', 'FMI'), ('UN_SDG', 'ONU - ODD'), ('AfDB', 'BAD')], max_length=50)),
                ('can_read', models.BooleanField(default=True)),
                ('can_export', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_data_source_access',
                'unique_together': {('user', 'source')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='users.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.role')),
            ],
            options={
                'db_table': 'users_role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
