version: '3.8'

services:
  # Base de données MongoDB (SEULEMENT)
  mongodb:
    image: mongo:7.0
    container_name: centralisation_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: centralisation_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - app_default

  # Application Django - DESACTIVE (lance manuellement avec runserver)
  # web:
  #   ...

  # Airflow - DESACTIVE (lance manuellement si besoin)
  # airflow-scheduler:
  #   ...
  
  # airflow-webserver:
  #   ...

volumes:
  mongodb_data:
    driver: local
    name: centralisation_mongodb_data
  mongodb_config:
    driver: local
    name: centralisation_mongodb_config

networks:
  app_default:
    driver: bridge
    name: app_default