# Generated by Django 5.2.8 on 2025-11-24 16:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'alerte", max_length=200)),
                ('alert_type', models.CharField(choices=[('brvm_variation', 'Variation BRVM'), ('debt_gdp_ratio', 'Ratio Dette/PIB'), ('inflation_rate', "Taux d'Inflation"), ('gdp_growth', 'Croissance PIB'), ('custom', 'Personnalisé')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('condition_type', models.CharField(choices=[('greater_than', 'Supérieur à'), ('less_than', 'Inférieur à'), ('equal_to', 'Égal à'), ('between', 'Entre')], default='greater_than', max_length=20)),
                ('threshold_value', models.FloatField(help_text='Valeur seuil')),
                ('threshold_value_max', models.FloatField(blank=True, help_text="Valeur seuil max (pour 'between')", null=True)),
                ('country_code', models.CharField(blank=True, help_text='Code pays (ex: CIV, BEN)', max_length=3)),
                ('stock_symbol', models.CharField(blank=True, help_text='Symbole action BRVM', max_length=20)),
                ('indicator_code', models.CharField(blank=True, help_text='Code indicateur', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('triggered', 'Déclenchée')], default='active', max_length=20)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_dashboard', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_value', models.FloatField()),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dashboard.alert')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_layout', models.JSONField(default=dict, help_text='Configuration widgets dashboard')),
                ('favorite_countries', models.JSONField(default=list, help_text='Codes pays favoris')),
                ('favorite_indicators', models.JSONField(default=list, help_text='Codes indicateurs favoris')),
                ('favorite_stocks', models.JSONField(default=list, help_text='Symboles actions BRVM favoris')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='dark', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence Utilisateur',
                'verbose_name_plural': 'Préférences Utilisateurs',
            },
        ),
    ]
